BusinessManager/Controllers/MedicalLeavesController.cs
using BusinessManager.Application.Interfaces.HR.Employee;
using BusinessManager.Application.ViewModel.HR.Employee.Work.ScheduleWork.MedicalLeave;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BusinessManager.Controllers
{
    public class MedicalLeavesController : Controller
    {
        private readonly IMedicalLeaveService _medicalLeaveService;
        private readonly IEmployeeService _employeeService;

        public MedicalLeavesController(IMedicalLeaveService medicalLeaveService, IEmployeeService employeeService)
        {
            _medicalLeaveService = medicalLeaveService;
            _employeeService = employeeService;
        }
        [HttpGet]
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            try
            {
                ViewBag.CurrentSort = sortOrder;
                ViewBag.StartDateSortParm = sortOrder == "startdate_desc" ? "startdate" : "startdate_desc";
                ViewBag.EndDateSortParm = sortOrder == "enddate_desc" ? "enddate" : "enddate_desc";
                if(searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }
                ViewBag.CurrentFilter = searchString;

                var pageSize = 10;
                var pageNumber = page ?? 1;
                var pagedMedicalLeaves = await _medicalLeaveService.GetMedicalLeavesListAsync(pageNumber, pageSize, searchString, sortOrder);
                return View(pagedMedicalLeaves);
            }
            catch (Exception ex)
            {
                return View("Error", ex); 
            }
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                ViewData["EmployeeId"] = id;
                var medicalLeaves = await _medicalLeaveService.GetMedicalLeaveByIdAsync(id);
                if(medicalLeaves == null)
                {
                    return NotFound();
                }
                return View(medicalLeaves);
            }
            catch(Exception ex)
            {
                return View("Error", ex);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create(int employeeId)
        {
            ViewData["EmployeeId"] = employeeId;
            var employee = await _employeeService.GetEmployeeByIdAsync(employeeId);
            if(employee != null)
            {
                var medicalLeavesViewModel = new MedicalLeaveViewModel
                {
                    EmployeeId = employee.Id,
                    FirstName = employee.FirstName,
                    LastName = employee.LastName,
                };
                return(View(medicalLeavesViewModel));
            }
            else
            {
                return NotFound();
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MedicalLeaveViewModel medicalLeave)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    var employee = await _employeeService.GetEmployeeByIdAsync(medicalLeave.EmployeeId);
                    if(employee == null)
                    {
                        return NotFound();
                    }
                    var overlapping = await _medicalLeaveService.FindOverlappingMedicalLeaves(medicalLeave.EmployeeId, medicalLeave.StartDate, medicalLeave.EndDate);
                    if (overlapping.Any())
                    {
                        ModelState.AddModelError(string.Empty, "Istnieje już zwolnienie lekarskie w podanym zakresie dat.");
                        ViewData["EmployeeId"] = medicalLeave.EmployeeId;
                        return View(medicalLeave);
                    }
                    var newMedicalLeave = new MedicalLeaveViewModel
                    {
                        EmployeeId = medicalLeave.EmployeeId,
                        FirstName = medicalLeave.FirstName,
                        LastName = medicalLeave.LastName,
                        StartDate = medicalLeave.StartDate,
                        EndDate = medicalLeave.EndDate
                    };
                    await _medicalLeaveService.CreateMedicalLeaveAsync(newMedicalLeave);
                    return RedirectToAction("Details", "Employee", new {id =  medicalLeave.EmployeeId});
                }
                ViewData["EmployeeId"] = medicalLeave.EmployeeId;
                return View(medicalLeave);
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id, int employeeId)
        {
            try
            {
                ViewData["EmployeeId"] = employeeId;
                var medicalLeavesViewModel = await _medicalLeaveService.GetMedicalLeaveForEdit(id);
                if(medicalLeavesViewModel == null)
                {
                    return NotFound();
                }
                return View(medicalLeavesViewModel);
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MedicalLeaveViewModel medicalLeave)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    await _medicalLeaveService.UpdateMedicalLeaveAsync(medicalLeave);
                    return RedirectToAction("Details", "Employee", new {id = medicalLeave.EmployeeId});
                }
                return View(medicalLeave);
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id, int employeeId)
        {
            try
            {
                var medicalLeaves = await _medicalLeaveService.DeleteMedicalLeaveAsync(id);
                if(medicalLeaves == null)
                {
                    return NotFound();
                }
                ViewData["EmployeeId"] = employeeId;
                return View(medicalLeaves);
            }
            catch(Exception ex)
            {
                return View("Error", ex);
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int employeeId)
        {
            try
            {
                ViewData["EmployeeId"] = employeeId;
                var result = await _medicalLeaveService.DeleteMedicalLeaveAsync(id);
                if (result)
                {
                    return RedirectToAction("Details", "Employee", new { id = employeeId });
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }
    }
}

BusinessManager/Views/MedicalLeaves/Create.cshtml
@model BusinessManager.Application.ViewModel.HR.Employee.Work.ScheduleWork.MedicalLeave.MedicalLeaveViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4 shadow p-4 mb-5 bg-white rounded">
    <div class="card">
        <div class="card-header">
            <h4>Create Medical Leaves</h4>
        </div>
        <div class="card-body">
            <form asp-action="Create" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="EmployeeId" value="@ViewData["EmployeeId"]" />

                <div class="form-group">
                    <label asp-for="FirstName" class="control-label">First Name:</label>
                    <input asp-for="FirstName" class="form-control" readonly />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="LastName" class="control-label">Last Name:</label>
                    <input asp-for="LastName" class="form-control" readonly />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="StartDate" class="control-label">Start Date:</label>
                    <input asp-for="StartDate" type="date" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="EndDate" class="control-label">End Date:</label>
                    <input asp-for="EndDate" type="date" class="form-control" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>

                <div class="form-group d-flex justify-content-between mt-4">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-controller="Employee" asp-action="Details" asp-route-id="@ViewData["EmployeeId"]" class="btn btn-outline-secondary">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BusinessManager/Views/MedicalLeaves/Delete.cshtml
@model BusinessManager.Application.ViewModel.HR.Employee.Work.ScheduleWork.MedicalLeave.MedicalLeaveViewModel

<div class="container mt-4 shadow p-4 mb-5 bg-white rounded">
    <div class="card">
        <div class="card-header bg-danger text-white">
            <h4>Delete Leave Request</h4>
        </div>
        <div class="card-body">
            <h5 class="card-title">Leave Request Details</h5>
            <hr />

            <dl class="row">
                <dt class="col-sm-3">First Name:</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.FirstName)</dd>

                <dt class="col-sm-3">Last Name:</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.LastName)</dd>

                <dt class="col-sm-3">Start Date:</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.StartDate)</dd>

                <dt class="col-sm-3">End Date:</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.EndDate)</dd>

            </dl>

            <form asp-action="Delete" method="post">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="EmployeeId" />

                <div class="text-center">
                    <button type="submit" class="btn btn-danger">Confirm Delete</button>
                    <a asp-controller="Employee" asp-action="Details" asp-route-Id="@Model.EmployeeId" class="btn btn-outline-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

BusinessManager/Views/MedicalLeaves/Details.cshtml
@model BusinessManager.Application.ViewModel.HR.Employee.Work.ScheduleWork.MedicalLeave.MedicalLeaveViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div class="container shadow p-4 mb-5 bg-white rounded">
    <div class="card mt-4">
        <div class="card-header">
            <h4 class="mb-0">Leave Request Details</h4>
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-3">First Name:</dt>
                <dd class="col-sm-9">@Model.FirstName</dd>

                <dt class="col-sm-3">Last Name:</dt>
                <dd class="col-sm-9">@Model.LastName</dd>

                <dt class="col-sm-3">Start Date:</dt>
                <dd class="col-sm-9">@Model.StartDate.ToString("yyyy-MM-dd")</dd>

                <dt class="col-sm-3">End Date:</dt>
                <dd class="col-sm-9">@Model.EndDate.ToString("yyyy-MM-dd")</dd>

                @{
                    var numberOfDays = (@Model.EndDate - @Model.StartDate).Days;
                }
                <p class="card-text"><strong>Number of Days:</strong> @numberOfDays</p>
                @if (numberOfDays > 30)
                {
                    <p class="card-text"><strong>Medical Examination Required:</strong> Yes</p>
                }

            </dl>

            <div class="mt-4">
                <a asp-controller="MedicalLeaves" asp-action="Edit" asp-route-employeeId="@Model.EmployeeId" asp-route-Id="@Model.Id" class="btn btn-primary btn-sm">Edit</a>
                <a asp-controller="MedicalLeaves" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger btn-sm mr-2">Delete</a>
                <a asp-controller="Employee" asp-action="Details" asp-route-Id="@Model.EmployeeId" class="btn btn-outline-secondary btn-sm mr-2">Employee Details</a>
                <a asp-controller="MedicalLeaves" asp-action="Index" class="btn btn-outline-secondary btn-sm">List Medical Leaves</a>
            </div>

        </div>
    </div>
</div>

BusinessManager/Views/MedicalLeaves/Edit.cshtml
@model BusinessManager.Application.ViewModel.HR.Employee.Work.ScheduleWork.MedicalLeave.MedicalLeaveViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4 shadow p-4 mb-5 bg-white rounded">
    <div class="card">
        <div class="card-header">
            <h4>Medical Leaves Edit</h4>
        </div>
        <div class="card-body">
            <form asp-action="Edit" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="Id" hidden="hidden" class="form-control" />
                <input type="hidden" asp-for="EmployeeId" value="@ViewData["EmployeeId"]" />

                <div class="form-group">
                    <label asp-for="FirstName" class="control-label">First Name:</label>
                    <input asp-for="FirstName" class="form-control" readonly />
                </div>

                <div class="form-group">
                    <label asp-for="LastName" class="control-label">Last Name:</label>
                    <input asp-for="LastName" class="form-control" readonly />
                </div>

                <div class="form-group">
                    <label asp-for="StartDate" class="control-label">Start Date:</label>
                    <input asp-for="StartDate" type="date" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="EndDate" class="control-label">End Date:</label>
                    <input asp-for="EndDate" type="date" class="form-control" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>

                <div class="form-group d-flex justify-content-between mt-4">
                    <input type="submit" value="Update" class="btn btn-primary" />
                    <a asp-controller="Employee" asp-action="Details" asp-route-Id="@Model.EmployeeId" class="btn btn-outline-secondary">Employee Details</a>
                    <a asp-controller="MedicalLeaves" asp-action="Index" class="btn btn-outline-danger">List Leave Request</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BusinessManager/Views/MedicalLeaves/Index.cshtml
@model PagedList.StaticPagedList<BusinessManager.Application.ViewModel.HR.Employee.Work.ScheduleWork.MedicalLeave.MedicalLeaveForListViewModel>

@{
    ViewData["Title"] = "Index";
    bool isFiltering = !string.IsNullOrEmpty(ViewBag.CurrentFilter);
}

<div class="container text-center shadow p-4 mb-5 bg-white rounded">
    <form asp-action="Index" method="get">
        <div class="d-flex justify-content-center m-lg-auto">
            <div class="col-lg-5">
                <h2>Medical Leave List</h2>
            </div>
            <div class="col-lg-4">
                <div class="input-group">
                    <input type="text" class="form-control" name="searchString" value="@ViewBag.CurrentFilter" placeholder="Search by name">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary">Search</button>
                        <a href="@Url.Action("Index", new { searchString = "", page = 1 })" class="btn btn-secondary">Reset</a>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div style="overflow-x:auto;">
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Nr.</th>
                    <th scope="col">
                        <a href="@Url.Action("Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })">Employee Name</a>
                    </th>
                    <th scope="col">
                        <a href="@Url.Action("Index", new { sortOrder = ViewBag.StartDateSortParm, currentFilter = ViewBag.CurrentFilter })">Start Date</a>
                    </th>
                    <th scope="col">
                        <a href="@Url.Action("Index", new { sortOrder = ViewBag.EndDateSortParm, currentFilter = ViewBag.CurrentFilter })">End Date</a>
                    </th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.TotalItemCount > 0)
                {
                    var counter = (Model.PageNumber - 1) * Model.PageSize + 1;
                    foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@counter</th>
                            <td>@item.FirstName @item.LastName</td>
                            <td>@item.StartDate.ToString("yyyy-MM-dd")</td>
                            <td>@item.EndDate.ToString("yyyy-MM-dd")</td>
                            <td class="d-flex justify-content-around">
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" })
                                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info btn-sm" })
                                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
                            </td>
                        </tr>
                        counter++;
                    }
                }
                else
                {
                    <tr class="alert alert-warning">
                        <td colspan="7"><strong>No Medical Leaves Data</strong></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="d-flex justify-content-between border-top pt-3 mt-3">
        <div>
            <p class="mb-0">Total Medical Leaves: @Model.TotalItemCount</p>
        </div>
        <div>
            <p class="mb-0">Page @(Model.PageNumber) of @(Model.PageCount)</p>
        </div>
        <div>
            @if (Model.HasPreviousPage)
            {
                @Html.ActionLink("Previous", "Index", new { page = Model.PageNumber - 1, searchString = ViewBag.CurrentFilter }, new { @class = "btn btn-primary" })
            }

            @if (!isFiltering && Model.PageNumber > 1)
            {
                @Html.ActionLink("Back to Start", "Index", new { page = 1 }, new { @class = "btn btn-secondary" })
            }

            @if (Model.HasNextPage)
            {
                @Html.ActionLink("Next", "Index", new { page = Model.PageNumber + 1, searchString = ViewBag.CurrentFilter }, new { @class = "btn btn-primary" })
            }
        </div>
    </div>
</div>